import React from 'react'
import { StyleSheet } from 'react-native';
let Dimensions = require('Dimensions');
//屏幕高度
let phoneheight = Dimensions.get('window').height
//屏幕宽度
let phoneWidth = Dimensions.get('window').width
export const styles = StyleSheet.create({
  //大课
  phpPrice:{
    height:100,
    flexDirection: 'column',
    backgroundColor:'white',
    marginTop:10,
    marginBottom:10,
    paddingLeft:10,
    paddingRight:10,
    paddingTop:5,
    paddingBottom:5,
    overflow:'scroll'
  },
  price:{
    flex:1,
    flexDirection:'row'
  },
  priceLeftFlex:{
    flex:0.6,
    fontSize:12,
  },
  priceRightFlex:{
    flex:0.4,
    fontSize:12,
  },
  SpecialPrice:{
    color:'red'
  },
  intro:{
    flex:3,
  },
  introFont:{
    fontSize:12,
  },
  listBg:{
    flex:1,
  },
  listItem:{
    height:100,
    width:'100%',
    flex:1,
    flexDirection: 'row',
    borderBottomWidth:1,
    borderColor:'#ebebeb',
    backgroundColor:'white',
    paddingLeft:20,
    paddingTop:10,
    paddingRight:20
  },
  listItemHeader:{
    flex:0.7,
    flexDirection: 'column',
  },
  listItemButton:{
    flex:0.3,
    justifyContent:'center',
    paddingRight:10
  },
  headerBox:{
    height:40,
    flexDirection: 'row',
  },
  header:{
    height:40,
    width:40,
    borderRadius:40
  },
  names:{
    flexDirection: 'column',
    height:40,
    marginLeft:10,
    flex:0.8,
  },
  name:{
    height:20,
    lineHeight:20,
    fontSize:14,
    fontWeight:'bold'
  },
  experience:{
    height:20,
    lineHeight:20,
    fontSize:12,
    flex:1
  },
  describeBox:{
    flexDirection: 'column',
  },
  formerlyBox:{
    flexDirection: 'row',
  },
  formerlyColor:{
    color:'rgb(133,133,133)',
    borderRightWidth:1,
    borderColor:'rgb(133,133,133)',
    marginRight:5,
    paddingRight:5,
    fontSize:12,
  },
  commentColor:{
    color:'rgb(133,133,133)',
    paddingRight:10,
    fontSize:12
  },
  messageBox:{
    backgroundColor:'white',
    flex:1
  },
  messageSearchBox:{
    flexDirection:'row',
    height:25,
    backgroundColor:'#ebebeb',
    marginLeft:20,
    marginRight:20,
    marginTop:10,
    marginBottom:10,
    borderRadius:5,
    alignItems:'center',
    justifyContent:'center',
  },
  iconSearch:{
    height:15,
    width:15
  },
  listMessage:{
    height:50,
    paddingLeft:20,
    paddingRight:20,
    flexDirection:'row',
    borderBottomWidth:1,
    borderColor:'#ebebeb',
    marginTop:10
  },
  listMessageBox:{
    flex:1
  },
  //小课
  smallcalssListBox:{
    backgroundColor:'white',
    height:120,
    flexDirection:'row',
    paddingLeft:20,
    paddingRight:20,
    paddingTop:10,
    paddingBottom:10,
    borderBottomWidth:1,
    borderColor:'#ebebeb'
  },
  smallclassImgBox:{
    height:100,
    width:130,
    backgroundColor:'#ebebeb'
  },
  smallclassImg:{
    height:100,
    width:130
  },
  smallclassTitleBox:{
    height:100,
    flex:1,
    marginLeft:10,
    flexDirection:'column'
  },
  smallcalssPrice:{
    height:20,
    lineHeight:20,
    color:'red',
    fontSize:14
  },
  smallclassTitle:{
    height:20,
    lineHeight:20,
    color:'#999',
    fontSize:16
  },
  LuckText:{
    height:20,
    lineHeight:20,
    color:'#999',
    fontSize:12
  },
  LuckFirendText:{
    height:40,
    lineHeight:20,
    fontSize:12
  },
  messageHeade:{
    height:40,
    width:40,
    borderRadius:20
  },
  messageTextBox:{
    flex:0.8,
    height:40,
    marginLeft:5
  },
  messageText:{
    height:20,
    lineHeight:20
  },
  messageTimeBox:{
    flex:0.2,
    height:40,
    alignItems:'center',
    justifyContent:'center'
  },
  warn:{
    height:20,
    width:20,
    borderRadius:10,
    backgroundColor:'rgb(25,160,148)',
    alignItems:'center',
    justifyContent:'center'
  },
  searchBox:{
    flex:1,
    backgroundColor:'white'
  },
  searchLine:{
    height:25,
    flexDirection:'row',
    paddingLeft:20,
    paddingRight:20,
    justifyContent:'space-between',
    alignItems:'center',
    marginTop:10
  },
  search:{
    flex:0.8,
    height:25,
    backgroundColor:'#ebebeb',
    borderRadius:3,
    alignItems:'center',
    flexDirection:'row',
    paddingLeft:5,
    paddingRight:5
  },
  canceBox:{
    alignItems:'center',
    justifyContent:'center',
    width:40,
    height:25
  },
  canceFont:{
    color:'rgb(25,160,148)',
    fontSize:15
  },
  searchInput:{
    height:15,
    lineHeight:15,
    flex:1,
    fontSize:13,
    color:'rgb(25,160,148)',
    padding: 0
  },
  chatBox:{
    flex:1,
    backgroundColor:'white',
  },
  messageListPersonal:{
    height:110,
    backgroundColor:'rgb(25,160,148)',
    borderRadius:5,
    marginTop:20,
    marginBottom:20
  },
  messageListPersonalBox:{
    height:70,
    flexDirection:'row',
    alignItems:'center',
    paddingLeft:20
  },
  messageListPersonalHeader:{
    height:50,
    width:50,
    borderRadius:25,
    marginRight:20
  },
  messageListPersonalTextBox:{
    flexDirection:'column',
    height:50
  },
  messageListPersonalUserNameBox:{
    flex:1,
    justifyContent:'center'
  },
  messageListPersonalUserNameText:{
    fontSize:15,
    color:'white'
  },
  messageListPersonalListBox:{
    flexDirection:'row',
    flex:1,
    height:25,
    alignItems:'center'
  },
  messageListPersonalListText:{
    fontSize:11,
    color:'white',
    borderRightWidth:1,
    borderColor:'white',
    marginRight:5,
    paddingRight:5
  },
  messageListPersonalButton:{
    borderTopWidth:1,
    height:40,
    borderColor:'white',
    justifyContent:'center',
    alignItems:'center'
  },
  messageListPersonalButtonText:{
    color:'white',
    fontSize:15
  },
  messageListsBox:{
    marginBottom:10,
  },
  messageListTimeBox:{
    flex:1,
    alignItems:'center',
    marginBottom:10,
  },
  messageListBox:{
    flexDirection:'row',
    paddingRight:80
  },
  messageContent:{
    backgroundColor:'#ebebeb',
    borderRadius:3,
    marginLeft:10,
    padding:10
  },
  keyBox:{
    flexDirection:'row',
    paddingTop:5,
    paddingBottom:5,
    justifyContent:'space-between',
    alignItems:'center',
    paddingLeft:5,
    paddingRight:5
  },
  keyInputBox:{
    flexDirection:'row',
    flex:0.9,
    backgroundColor:'#ebebeb',
    borderRadius:15
  },
  keyInput:{
    padding:0,
    width:'100%',
    marginLeft:10,
    fontSize:15
  },
  sendButtonBox:{
    width:60,
    alignSelf:'flex-end'
  },
  myUsernameBox:{
    height:80,
    backgroundColor:'rgb(25,160,148)',
    flexDirection:'row',
    paddingRight:10,
    paddingLeft:10,
    alignItems:'center',
  },
  personalDataBox:{
    height:60,
    flex:1,
    flexDirection:'column',
    marginLeft:10,
  },
  personalDataText:{
    height:30,
    fontSize:18,
    color:'white',
    lineHeight: 30
  },
  personalDataRate:{
    height:40,
    flexDirection:'column',
  },
  personalDataRateText:{
    height:20,
    fontSize:14,
    color:'white',
    alignItems:'center'
  },
  myCenterListBox:{
    flexDirection:'row',
    height:40,
    paddingLeft:10,
    paddingRight:10,
    backgroundColor:'white',
    alignItems:'center',
    borderBottomWidth:1,
    borderColor:'rgb(234,233,239)'
  },
  myCenterListIconBox:{
    height:30,
    width:30,
    alignItems:'center',
    justifyContent:'center'
  },
  myCenterListIconRightBox:{
    height:20,
    width:20,
    alignItems:'center',
  },
  myCenterListText:{
    flex:1,
    marginLeft:10,
    color:'#111'
  },
  masterDetailsBox:{
    height:phoneheight,
    width:phoneWidth,
    position: 'absolute',
    backgroundColor:'rgb(234,233,239)',
    flex:1
  },
  MasterHeaderBox:{
    position:'relative',
    bottom:35,
    paddingLeft:20,
    flex:1,
    flexDirection:'row'
  },
  MasterHeaderPhoto:{
    height:70,
    width:70,
    borderRadius:70,
    borderColor:'white',
    borderWidth:2,
  },
  MasterHeaderTitleBox:{
    height:70,
    flex:1,
    flexDirection:'column',
    marginLeft:5
  },
  MasterNameBox:{
    height:35,
    flexDirection:'row'
  },
  MasterName:{
    fontSize:18,
    lineHeight:35,
    color:'white',
    fontWeight:'bold',
    marginRight:10
  },
  MasterResume:{
    fontSize:12,
    lineHeight:35,
    color:'white',
    marginRight:5
  },
  MasterTitle:{
    fontSize:18,
    textAlign:'center',
    height:24,
    lineHeight:24,
    color:'rgb(25,160,148)',
    marginBottom:10,
    fontWeight:'bold'
  },
  MasterTitleBox:{
    backgroundColor:'white',
    marginBottom:20,
    paddingLeft:20,
    paddingRight:20,
    paddingTop:10,
    paddingBottom:10
  },
  JudgeMasterTitleBox:{
    backgroundColor:'white',
    marginBottom:20,
    paddingLeft:20,
    paddingRight:20,
    paddingTop:10,
  },
  // 前辈作品列表
  JudgeMasterDemoBox:{
    height:100,
    flexDirection:'row',
  },
  MasterTitleRowBox:{
    height:20 ,
    flexDirection:'row'
  },
  MasterTitleKey:{
    lineHeight:20,
    fontSize:14,
    color:'#333',
    width:90
  },
  MasterDemoBox:{
    height:100,
    flexDirection:'row',
    marginBottom:20
  },
  DemoImgBox:{
    height:100,
    width:100,
    backgroundColor:'#ebebeb'
  },
  DemoImg:{
    height:100,
    width:100
  },
  DemoTextBox:{
    flex:1,
    flexDirection:'column',
    paddingLeft:10
  },
  DemoTextTitleBox:{
    height:20
  },
  DemoText:{
    lineHeight:20,
    color:'#999',
    fontSize:14
  },
  MasterResumekeys:{
    color:'#999',
    lineHeight:20,
    fontSize:14
  },
  ApprenticeListBox:{
    height:65,
    flexDirection:'row',
    paddingTop:5,
    paddingBottom:10,
    paddingLeft:20,
    paddingRight:20,
    backgroundColor:'white',

  },
  ApprenticePhoto:{
    height:50,
    width:50,
    borderRadius:50
  },
  ApprenticeNmaeBox:{
    flex:0.8,
    flexDirection:'column',
    marginLeft:5
  },
  ApprenticeNmae:{
    lineHeight:25,
    fontSize:13,
    color:'#333'
  },
  ApprenticeTime:{
    lineHeight:25,
    fontSize:13,
    color:'#999'
  },
  projectNum:{
    textAlign:'center',
    fontSize:20,
    color:'rgb(25,160,148)',
    marginBottom:20,
    marginTop:10
  },
  // 大课详情
  BigClassDetailsTextModoulBox:{
    backgroundColor:'white',
    marginTop:20,
    marginLeft:20,
    marginRight:20,
    borderRadius:6,
    padding:20
  },
  BigClassDetailsTextModoulText:{
    color:'rgb(25,160,148)',
    fontWeight:'500',
    fontSize:16
  },
  BigClassDetailsTextDetailsTitle:{
    fontSize:14,
    fontWeight:'500',
    color:'#666',
    marginBottom:5
  },
  BigClassDetailsHeaderBox:{
    backgroundColor:'rgb(25,160,148)',
    height:120,
    marginTop:10,
    marginLeft:20,
    marginRight:20,
    borderRadius:6
  },
  BigClassDetailsHeaderClassTitleBox:{
    marginLeft:20,
    marginTop:10,
    height:20
  },
  BigClassDetailsHeaderClassTitleText:{
    color:'white',
    fontWeight:'500',
    fontSize:16
  },
  BigClassDetailsHeaderTitleBox:{
    marginLeft:20,
    marginRight:20,
    height:40,
    alignItems:'center'
  },
  BigClassDetailsHeaderTitle:{
    color:'white',
    fontWeight:'500',
    fontSize:40
  },
  BigClassDetailsFooterBox:{
    marginLeft:10,
    marginRight:10,
    marginTop:10,
    height:20,
    flexDirection:'row'
  },
  BigClassDetailsFooterText:{
    color:'white',
    fontSize:12,
  },
  // 小课详情
  SmallClassModalBox:{
    alignItems:'center',
    justifyContent:'center',
    flex:1,
    flexDirection:'row',
    backgroundColor:'rgba(0,0,0,0.7)'
  },
  ModalBox:{
    height:300,
    flex:1,
    marginRight:20,
    marginLeft:20,
    backgroundColor:'white',
    borderRadius:10,
    borderColor:'#ebebeb',
    borderWidth:1,
    overflow:'hidden'
  },
  closeBox:{
    height:20,
    flexDirection:'column',
    marginTop:10,
    marginBottom:10
  },
  close:{
    height:20,
    width:20,
    borderRadius:20,
    alignSelf:'flex-end',
    marginRight:10
  },
  smallContentBox:{
    height:120,
    flexDirection:'row',
    marginBottom:10
  },
  smallContentImgBox:{
    height:120,
    width:120,
    marginLeft:10,
    marginRight:5
  },
  smallModalTextBox:{
    height:120,
    marginRight:10,
    flex:1,
    flexDirection:'column'
  },
  smallModalText:{
    fontSize:14,
    color:'#333',
    lineHeight:17
  },
  modalContent:{
    height:80,
    paddingLeft:5,
    paddingRight:5,
    flexDirection:'row'
  },
  shoppinButoon:{
    height:30,
    width:60,
    alignSelf:'center'
  },
  //求学中
  StudyBox:{
    marginRight:20,
    backgroundColor:'#fff',
    marginTop:10,
    marginLeft:20,
    borderRadius:10,
  },
  StudyTextTitle:{
    fontSize:18,
    color:'rgb(25,160,148)',
    textAlign:'center',
    marginTop:10,
    marginBottom: 10
  },
  StudyMasterBox:{
    marginTop:10,
    marginLeft:10,
    marginRight:10
  },
  StudyMasterHeaderBox:{
    height:100,
    flexDirection:'row',
    alignItems:'center',
    paddingTop:10,
    paddingBottom:10
  },
  StudyMasterImage:{
    height:100,
    width:100,
    borderRadius:100
  },
  StudyMasterTextBox:{
    height:100,
    flex:1,
    marginLeft:5,
    flexDirection:'column'
  },
  StudyMasterTextListBox:{
    height:15
  },
  StudyText:{
    color:"#333",
    fontSize:12
  },
  Studyyidai:{
    paddingRight:5,
    borderRightWidth:1,
    borderColor:'#555'
  },
  StudyyidaiText:{
    fontSize:12,
    color:'#555'
  },
  StudyMasterDataBox:{
    paddingTop:5,
    marginTop:10,
    borderTopWidth:1,
    borderColor:'#ebebeb'
  },
  StudyMasterDataTitle:{
    height:20,
    fontSize:16,
    fontWeight:'500',
    color:'#333'
  },
  StudyMasterDataText:{
    color:"#333",
    height:20,
    fontSize:14
  },
  StudyMasterDataTextColor:{
    color:'#777'
  },
  StudyMasterButtonBox:{
    flexDirection:'row',
    justifyContent:'center',
    marginTop:10,
    borderTopWidth:1,
    borderColor:'#ebebeb',
    paddingTop: 10
  },
  StudyMasterButtonLeftBox:{
    height:40,
    width: 100
  },
  //我的任务
  LableBox:{
    backgroundColor:'rgb(25,160,148)',
    alignItems:'center',
    justifyContent:'center',
    marginLeft:5,
    paddingLeft:5,
    paddingRight:5,
    borderRadius:3
  },
  //学员管理
  ManagementLableBox:{
    backgroundColor:'rgb(25,160,148)',
    justifyContent:'center',
    borderRadius:3,
    marginLeft:5,
    paddingLeft:5,
    paddingRight:5
  },
  ManagementLableTitle:{
    color:'#fff',
    fontSize:12
  },
  RecommendExplainTitle:{
    fontSize:14,
    color:'#333',
    marginTop:5,
    marginBottom:5
  },
  RecommendExplainColor:{
    fontSize:12,
    color:'#666'
  },
  //账户
  AccountListBox:{
    padding:10,
    backgroundColor:'#fff',
    marginTop:10,
    flexDirection: 'row'
  },
  //财务总览
  FinanceOverviewListBox:{
    padding:10,
    paddingLeft:10,
    marginTop:10,
    backgroundColor:'#fff'
  },
//设置用户名
  SetUserNameInputBox:{
    flexDirection: 'row',
    height: 40,
    backgroundColor: '#fff',
    marginTop:20,
    borderWidth: 1,
    borderColor: '#ebebeb',
    alignItems: 'center',
    paddingLeft: 10,
    paddingRight: 10
  },
  SetUserNameInput:{
    padding: 0,
    fontSize:16 ,
    flex:1
  },
  SetUserNameButton:{
    height: 40,
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'center'
  },
  //账号设置
  SetUserListBox:{
    height:60,
    backgroundColor:'#fff',
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 10
  },
  SetUserListTitle:{
    color:'#000',
    fontSize: 16,
    marginLeft: 20
  },
  //登录
  LoginBox:{
    backgroundColor: '#fff',
    flex:1,
    padding:10
  },
  LoginInput:{
    borderBottomWidth:0,
    paddingRight: 0,
    marginLeft:0
  },
  LoginButton:{
    backgroundColor: 'rgb(25,160,148)',
    borderRadius: 3,
    padding: 10
  },
  LoginButtonText:{
    color:'#fff',
    alignSelf: 'center'
  },
  LoginIconBox:{
    textAlign: 'center',
    fontSize: 14,
    color:'#999'
  },
  LoginButtonTitle:{
    color:'rgb(25,160,148)',
    alignSelf: 'center'
  },
  LoginIconViewBox:{
    flex:0.5,
    alignItems: 'center'
  },
  LoginSendCode:{
    backgroundColor: 'rgb(25,160,148)',
    borderRadius: 3,
    padding: 3
  },
  goLoginBox:{
    flex:1,
    alignItems: 'center',
    justifyContent: 'center'
  },
  goLoginButton:{
    padding:5,
    borderRadius: 3,
    backgroundColor: 'rgb(25,160,148)',
    justifyContent: 'center'
  }
});
